spring:
  application:
    name: app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: "dev"


rsa:
  public-key: classpath:certs/public.pem

admin:
  email: hexlet@example.com
  password: qwerty