spring:
  application:
    name: app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /api/documentation/docs.html
  api-docs:
    path: /api/api-docs

rsa:
  public-key: classpath:certs/public.pem

sentry:
  enabled: false

admin:
  email: hexlet@example.com
  password: qwerty